version: 2.0
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk 
    steps:
      - checkout
      - run:
          name: Run the gradle test
          command: gradle test
      - run:
          name: Run the gradle jar build
          command: gradle jar
      - store_test_results:
          path: build/test-results
      - store_artifacts:
          path: build/libs
          destination: prefix
